select * from SYS_USER;
truncate table SYS_USER;
SELECT USER_ID FROM SYS_USER ORDER BY USER_ID DESC LIMIT 1;

DROP PROCEDURE strUserCreateUpdate;
DELIMITER $$
CREATE PROCEDURE strUserCreateUpdate
(
	IN _USER_ID INT, 
    IN _USE_NAME VARCHAR(50),
    IN _USE_PASSWORD VARCHAR(50), 
    IN _USE_IMAGE_PROFILE TEXT
)	
BEGIN
DECLARE last_id INT;
SET last_id = (SELECT USER_ID FROM SYS_USER ORDER BY USER_ID DESC LIMIT 1);
	INSERT INTO SYS_USER (USER_ID, USE_NAME, USE_USER_NAME, USE_PASSWORD, USE_IMAGE_PROFILE, USE_STATUS)
    VALUES (NULL, _USE_NAME, CONCAT(_USE_NAME, last_id + 1), _USE_PASSWORD, _USE_IMAGE_PROFILE, 1)
    ON DUPLICATE KEY UPDATE
    USE_NAME = _USE_NAME, USE_PASSWORD = _USE_PASSWORD;
    SELECT LAST_INSERT_ID();
END $$
DELIMITER ;