<?php
$title = 'Nuevo usuario';
$this->headTitle($title);

/** @var PhpRenderer|HelperTrait $this */
/** @var Users|Form|UsersForm $form */
?>

    <h4 class="d-flex justify-content-between align-items-center mb-3 mt-3">
        <span class="text-muted"><?=$title?></span>
    </h4>

<?php

$name = $form->get('usr_name');
$name->setAttribute('class', 'form-control');

$middleName = $form->get('usr_middle_name');
$middleName->setAttribute('class', 'form-control');

$mail = $form->get('usr_email');
$mail->setAttribute('class', 'form-control');

$submitButton = $form->get('submit');
$submitButton->setAttribute('class', 'btn btn-primary');


$form->setAttribute('action', $this->url(null, ['action' => 'create']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('usr_users_id'));
?>
<div class="form-group">
    <?= $this->formLabel($name); ?>
    <?= $this->formElement($name); ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block text-danger']); ?>
</div>
<div class="form-group">
    <?= $this->formLabel($middleName); ?>
    <?= $this->formElement($middleName); ?>
    <?= $this->formElementErrors()->render($middleName, ['class' => 'help-block text-danger']); ?>
</div>
<div class="form-group">
    <?= $this->formLabel($mail); ?>
    <?= $this->formElement($mail); ?>
    <?= $this->formElementErrors()->render($mail, ['class' => 'help-block text-danger']); ?></div>
<div class="form-group">
    <?php echo $this->formSubmit($submitButton); ?>
</div>
<div class="form-group">
    <?php echo $this->form()->closeTag(); ?>
</div>
