<?php
// module/Album/view/users/users/index.phtml:
/** @var Users $table */


$title = 'Usuarios';
$this->headTitle($title);
?>
<div id="app">
    {{message}}
    <pre>
        {{ dataUsers }}
    </pre>
    <table>
        <thead>
            <th>Nombre</th>
        </thead>
        <tbody>
            <tr>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>

<script>


    const { createApp } = Vue

    createApp({
        data() {
            return {
                message: 'Hello Vue!'
            }
        }
    }).mount('#app')
</script>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url(null,[
        'controller' => 'users',
        'action' => 'create'
    ]); ?>">Nuevo usuario</a>
</p>
<table class="table" >
    <tr>
        <th>Nombre</th>
        <th>Correo electrónico</th>
        <th>Estatus</th>
    </tr>
    <?php foreach ($table as $user) : ?>
        <tr>
            <td><?= $this->escapeHtml($user->usr_name) ?></td>
            <td><?= $this->escapeHtml($user->usr_email) ?></td>
            <td>
                <a href="<?= $this->url(null, ['action' => 'edit', 'id' => $user->usr_users_id]) ?>">Edit</a>
                <a href="<?= $this->url(null, ['action' => 'delete', 'id' => $user->usr_users_id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>